--CREATE DATABASE TableRelations
--USE TableRelations

CREATE TABLE Passports
(
PassportID INT,
PassportNumber VARCHAR(12) NOT NULL,
CONSTRAINT PK_PassportID PRIMARY KEY (PassportID),
CONSTRAINT UQ_PassportNumber UNIQUE (PassportNumber)
)

CREATE TABLE Persons
(
PersonID INT IDENTITY,
FirstName VARCHAR(50) NOT NULL,
Salary DECIMAL(15,2) NOT NULL,
PassportID INT  NOT NULL

CONSTRAINT PK_PersonID PRIMARY KEY (PersonID),
CONSTRAINT FK_PersonsPassport FOREIGN KEY (PassportID)
REFERENCES Passports(PassportID),
CONSTRAINT UQ_PassportID UNIQUE (PassportID)
)


INSERT INTO Passports VALUES
(101,'N34FG21B'),
(102,'K65LO4R7'),
(103,'ZE657QP2')

INSERT INTO Persons VALUES 
('Roberto',43300.00,102),
('Tom',56100.00,103),
('Yana',60200.00,101)
