CREATE DATABASE WMS
USE WMS

CREATE TABLE Clients
(ClientId INT PRIMARY KEY IDENTITY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Phone CHAR(12) CHECK(LEN(Phone)=12) NOT NULL
)

CREATE TABLE Mechanics
(MechanicId INT PRIMARY KEY IDENTITY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
[Address] VARCHAR(255) NOT NULL
)

CREATE TABLE Models
(ModelId INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50) UNIQUE NOT NULL 
)

CREATE TABLE Jobs
(JobId INT PRIMARY KEY IDENTITY,
ModelId INT FOREIGN KEY REFERENCES Models NOT NULL,
[Status] VARCHAR(11) DEFAULT 'Pending' CHECK([Status] IN( 'Pending', 'In Progress', 'Finished')) NOT NULL,
ClientId INT FOREIGN KEY REFERENCES Clients NOT NULL,
MechanicId INT FOREIGN KEY REFERENCES Mechanics,

IssueDate DATE NOT NULL,
FinishDate DATE
)

CREATE TABLE Orders
(OrderId INT PRIMARY KEY IDENTITY,
JobId INT FOREIGN KEY REFERENCES Jobs NOT NULL, 
IssueDate DATE,
Delivered BIT DEFAULT 0 NOT NULL
)

CREATE TABLE Vendors
(VendorId INT PRIMARY KEY  IDENTITY,
[Name] VARCHAR(50) UNIQUE NOT NULL, 
)

CREATE TABLE Parts
(PartId INT PRIMARY KEY IDENTITY,
SerialNumber VARCHAR(50) UNIQUE NOT NULL,
[Description] VARCHAR(255),
Price DECIMAL(6,2) CHECK(Price>0 AND Price<9999.99) NOT NULL, 
VendorId INT FOREIGN KEY REFERENCES Vendors NOT NULL,
StockQty INT CHECK((StockQty>=0)) DEFAULT 0  NOT NULL 
)

CREATE TABLE OrderParts
(OrderId INT FOREIGN KEY REFERENCES Orders NOT NULL,
PartId INT FOREIGN KEY REFERENCES Parts NOT NULL,
Quantity INT CHECK(Quantity>0) DEFAULT 1 NOT NULL

CONSTRAINT PK_OrdersParts PRIMARY KEY (OrderID, PartID)
)

CREATE TABLE PartsNeeded
(JobId INT FOREIGN KEY REFERENCES Jobs NOT NULL,
PartId INT FOREIGN KEY REFERENCES Parts NOT NULL,
Quantity INT CHECK(Quantity>0) DEFAULT 1 NOT NULL

CONSTRAINT PK_JobsParts PRIMARY KEY (JobID, PartID)
)